name: ETCD daily update build(latest 70 tags)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2 * * 6

  jobs:
    prepare:
      runs-on: ubuntu-latest
      outputs:
        versions: ${{ steps.set-versions.outputs.versions }}
      steps:
        - name: Get latest patch versions of etcd
        - id: set-tags
          run: |
            TAGS=$(curl -s "https://api.github.com/repos/etcd-io/etcd/tags?per_page=100&page=1" | jq -r '.[].name | sub("^v";"")')
            #            TAGS=$(curl -s https://api.github.com/repos/etcd-io/etcd/releases | jq -r '.[].tag_name' | grep -E '^v[0-9]' | head -n 70 | jq -R . | jq -cs .)
            echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

  build-binaries:
    needs: get-tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.get-tags.outputs.tags) }}
    env:
      DOCKER_VERSION: ${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          #          ref: ${{ matrix.tag }}
          ref: main

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker Binaries
        run: |
          docker buildx build --platform linux/loong64 -t etcd-static-loong64:${{ matrix.tag }} --build-arg ETCD_VERSION=${{ matrix.tag }} --build-arg https_proxy=${https_proxy} -f binaries/Dockerfile . --load


      - name: Extract Binary Artifacts
        run: |
          mkdir -p dist
          docker run --rm -v ${{ github.workspace }}/dist:/out \
          etcd-static-loong64:${{ matrix.tag }} \
          bash -c 'cp /opt/* /out/ || true'

      - name: Upload Binary Artifacts
        run: |
          ls -al dist
          gh release upload ${{ matrix.tag }} -R ${{ github.repository }} dist/* || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
